### PR TITLE
Design tweaks

### PR DESCRIPTION
**Pull request by AshenI99**
### Problem

Fixed some design issues in the latest design update which mentioned here. [Issue #188](https://github.com/curaOS/source/issues/188)

### CODE REVIEW

**Comment by achrafismyname** [comment]
Hey @AshenI99 can you send the preview link to Lucia and review this changes with her, she understand the design stuff better

**Comment by achrafismyname** [comment]
The code seems good. 
Just on thing you missed is to update the dark mode logo
image

**Review by achrafismyname — CHANGES_REQUESTED** [review]
dark mode buttons on mobile looks asymmetrical
image

**Comment by devey** [comment]
> The code seems good. Just on thing you missed is to update the dark mode logo image

Is it me or know the canvas for art now is smaller @achrafismyname @AshenI99 ?

Screenshot 2022-01-03 at 15 35 16

**Comment by achrafismyname** [comment]
Hey @devey, yeah Lucia requested that and some other changes

**Comment by AshenI99** [comment]
> > The code seems good. Just on thing you missed is to update the dark mode logo image
> 

Hi @devey, could you tell me which logo are you referring?
Right now, we have one logo for dark mode and another one for normal mode.

**Pull request merged**
