### PR TITLE
Randomized homepage project

### PR DESCRIPTION
**Pull request by achrafismyname**
The reason I randomized the project page inside `useEffect` instead of doing it directly in `useState` is that Image Component doesn't update correctly, not sure why it happens but my guess it's something to do with NextJs cache. `useEffect` makes sure to change the page only after the component is settled.

### CODE REVIEW

**Comment by devey** [comment]
> Component doesn't update correctly, not sure why it happens but my guess it's something to do with NextJs cache

@achrafismyname Could you look into what's happening? Cause locally it works fine, it's just when it's deployed on Vercel that gives problems. The version you pushed is not optimal as it at always shows the first slide before jumping to the random one.

**Comment by achrafismyname** [comment]
Ok, I'll look more into that

**Comment by achrafismyname** [comment]
https://github.com/vercel/next.js/issues/10608

The only solution is to use `useEffect` or disable SSR

**Comment by achrafismyname** [comment]
Instead of showing the first slide, i'll put a loading animation. Hopefully this makes it look better

**Comment by achrafismyname** [comment]
I removed the slide, until we random the first project slide.

I don't know if SEO matters in this project, but the projects in this page can't be crawled because they are all browser rendered. Before we had 1 project that can be seen by crawling bots, after this change zero can be seen.

**Comment by devey** [comment]
As said in that issue linked:
> Generally I'd just recommend not randomly shuffling stuff in the UI

I think there could have been a better solution here in general, but it's a minor adjustment and the homepage will probably have more iteration in the future. Let's merge it! 😄

**Review by devey — APPROVED** [review]

**Pull request merged**
