### PR TITLE
Removing redundant theme and assets files

### PR DESCRIPTION
**Pull request by achrafismyname**
### Goal
Make `theme.ts` + `assets` exportable from `@cura/components` and import them to  the `frontend` so we don't have redundant files

### Steps
- [x] rename `public` folder to `assets` because it makes more sense
- [x] add script to `package.json` for copying `assets` to `dist` folder
- [x] move `theme.ts` inside `/src`. So when building the folder structure of `/dist` stays the same 
- [x] make `theme.ts` exportable from `@cura/components`
- [x] avoid exporting images from `@cura/components`, and let frontend define images
- [x] rename `assets/fonts/style.css` to `assets/fonts/index.css`. So we can import it the frontend easily
- [x] import `theme` from `@cura/components` in `frontend/theme.ts`
- [x] add removed gradients images from `@cura/components` to `frontend`
- [x] add logo to `frontend` 
- [x] Import `fonts` from `@cura/components` to `frontend`
- [x] make sure everything is working fine and improvise

### CODE REVIEW

**Comment by achrafismyname** [comment]
https://github.com/curaOS/source/blob/9af5fc1d98cb7a41eb0a21f80e0162a514cf2319/packages/components/src/theme.ts#L3-L7
Imported Images in `@cura/components` causes an error in the frontend

The error:
````
Next.js: You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file
````

### Possible solutions
- Make `Next.js` support loading images
- Avoid exporting images from `@cura/components`, and let frontend define images
- Encode images inside `@cura/components` to base64

**Comment by devey** [comment]
@achrafismyname I would say the second point. The goal is to be able to define branding as the logo from out of the components so this would be something you better pass from the front-end.

**Comment by achrafismyname** [comment]
## Summary

I made `theme.ts` exportable from `@cura/components`, and replaced styles inside `frontend/theme.ts` with it, while keeping styles that are unique to the frontend inside `frontend/theme.ts`.
Also, moved `theme.ts` from `components/theme.ts` to `components/src/theme.ts` because all publishable stuff should go in `src`.

--- 

I removed the fonts from `frontend` and imported them directly from `@cura/components/dist/assets/fonts`. To do that I had to add a script to `components/package.json` which copy `/assets` to `/dist` on each build.
And I renamed `components/public` folder to `assets`, because it makes more sense because they are not public.

--- 

And from your suggestion, I removed all images from `@cura/components` and defined them from the frontend instead.
To do that, I added `logo` prop to `Header` component. And for gradients that are images, I replaced them with a CSS gradient in `@cura/components` but in the frontend I used the images from design.

--- 
###  Other notes
- Vercel deployement won't work until we bump `@cura/components` because the package structure changed.

**Review by devey — APPROVED** [review]
Some things could be improved and noticed a couple of choices that might cause some trouble down the road, but looks fine for now! Thanks for cleaning up!

**Pull request merged**
