### PR TITLE
Frontend | adding NFT preview to claim_design

### PR DESCRIPTION
**Pull request by achrafismyname**

### CODE REVIEW

**Comment by devey** [comment]
@achrafismyname I forgot to merge this first. 😌 Could you try to rebase it?

**Comment by devey** [comment]
I guess to merge this @achrafismyname we also need to deploy new contracts for the contracts? Let's do that then we are done with `cNFT` on `cura/source`

**Comment by achrafismyname** [comment]
@devey, it works but we'll fall into this issue #189. And we would have to detect the type of each URI before displaying it
The issue is that for the old NFTs, `media` is still the iframe URI, and for the new NFTs minted using this PR are images. 

But yeah, that's good idea. Let's keep it until we are done from `cNFT`, so we can give it a fresh start

**Comment by achrafismyname** [comment]
moved to #194

**Pull request closed without merging**
